version: "3.7"
services:
  redis:
    image: "redis:latest"
    restart: always

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=scraper
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  server:
    build:
      context: ./apps/server
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USER: root
      DB_PASSWORD: toor
      DB_NAME: scraper
      REDIS_URL: redis://localhost:6379
    volumes:
      - ./server-data:/app/data

  client:
    build:
      context: ./apps/client
    ports:
      - "3000:3000"
    depends_on:
      - server
