export const userKey = 'scUser'
export const baseURL = 'http://localhost:8080'
export const accessTokenKey = 'scAccessToken'
export const refreshTokenKey = 'scRefreshToken'
export const sampleCSV = 'https://drive.google.com/file/d/19_7X0mIP_qa3cTK6n8CviyUnZyGegEdV/view'
